<a href="https://colab.research.google.com/github/agrimasharma00-code/Deep_Learning/blob/main/Basics_DL_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [ ]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [ ]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [ ]:
X= df[['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water']]
y= df['needs_water']

**NORMALOZATION (MIN-MAZ SCALING)**

In [ ]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [ ]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours  needs_water
0        0.066667         0.9375        0.727273          1.0
1        0.133333         0.6875        0.636364          1.0
2        0.200000         0.4375        0.545455          1.0
3        0.266667         0.1875        0.272727          0.0
4        0.466667         0.5625        0.636364          0.0
5        0.733333         0.6875        0.818182          0.0
6        0.400000         0.0000        0.181818          0.0
7        0.173333         0.1875        0.818182          1.0
8        0.533333         1.0000        1.000000          0.0
9        0.000000         0.3125        0.363636          1.0
10       1.000000         0.8750        0.727273          0.0
11       0.293333         0.8750        0.909091          1.0
12       0.666667         0.1250        0.090909          0.0
13       0.866667         0.3750        0.454545          0.0
14       0.093333         0.0625        0.000000          1.0
15       0.333333         0.6250        0.727273          1.0

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42, stratify=y
)

In [ ]:
model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation= 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [ ]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
history=model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,
    batch_size=1,
    verbose=1
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5000 - loss: 0.7549 - val_accuracy: 0.5000 - val_loss: 0.7205
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5000 - loss: 0.7429 - val_accuracy: 0.5000 - val_loss: 0.7134
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5000 - loss: 0.7315 - val_accuracy: 0.5000 - val_loss: 0.7060
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7194 - val_accuracy: 0.5000 - val_loss: 0.6978
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5000 - loss: 0.7074 - val_accuracy: 0.5000 - val_loss: 0.6903
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6956 - val_accuracy: 0.5000 - val_loss: 0.6829
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5000 - loss: 0.6840 - val_accuracy: 0.5000 - val_loss: 0.6759
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5000 - loss: 0.6727 - val_accuracy: 0.5000 - val_loss: 0.6680
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6615 - val_accuracy: 0.7500 - val_loss: 0.6597
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6505 - val_accuracy: 0.7500 - val_loss: 0.6515
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.6408 - val_accuracy: 0.7500 - val_loss: 0.6452
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.6318 - val_accuracy: 1.0000 - val_loss: 0.6392
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6667 - loss: 0.6233 - val_accuracy: 1.0000 - val_loss: 0.6333
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.6150 - val_accuracy: 1.0000 - val_loss: 0.6274
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.6068 - val_accuracy: 1.0000 - val_loss: 0.6213
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.5988 - val_accuracy: 1.0000 - val_loss: 0.6161
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5898 - val_accuracy: 1.0000 - val_loss: 0.6099
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5828 - val_accuracy: 1.0000 - val_loss: 0.6050
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5748 - val_accuracy: 1.0000 - val_loss: 0.6002
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5667 - val_accuracy: 1.0000 - val_loss: 0.5954
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.5589 - val_accuracy: 1.0000 - val_loss: 0.5907
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8333 - loss: 0.5507 - val_accuracy: 1.0000 - val_loss: 0.5863
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5432 - val_accuracy: 1.0000 - val_loss: 0.5809
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.5356 - val_accuracy: 1.0000 - val_loss: 0.5756
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.5279 - val_accuracy: 1.0000 - val_loss: 0.5703
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.5203 - val_accuracy: 1.0000 - val_loss: 0.5648
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.5129 - val_accuracy: 1.0000 - val_loss: 0.5584
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.5062 - val_accuracy: 1.0000 - val_loss: 0.5533
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.4990 - val_accuracy: 1.0000 - val_loss: 0.5479
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.4919 - val_accuracy: 1.0000 - val_loss: 0.5426
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.4846 - val_accuracy: 1.0000 - val_loss: 0.5368
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4779 - val_accuracy: 1.0000 - val_loss: 0.5326
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.4707 - val_accuracy: 1.0000 - val_loss: 0.5284
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.4637 - val_accuracy: 1.0000 - val_loss: 0.5228
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.4570 - val_accuracy: 1.0000 - val_loss: 0.5185
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.4505 - val_accuracy: 1.0000 - val_loss: 0.5127
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.4439 - val_accuracy: 1.0000 - val_loss: 0.5082
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.4374 - val_accuracy: 1.0000 - val_loss: 0.5026
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.4308 - val_accuracy: 1.0000 - val_loss: 0.4970
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4244 - val_accuracy: 1.0000 - val_loss: 0.4928
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.4183 - val_accuracy: 1.0000 - val_loss: 0.4875
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.4120 - val_accuracy: 1.0000 - val_loss: 0.4812
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.4056 - val_accuracy: 1.0000 - val_loss: 0.4751
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - accuracy: 1.0000 - loss: 0.3993 - val_accuracy: 1.0000 - val_loss: 0.4698
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 61ms/step - accuracy: 1.0000 - loss: 0.3937 - val_accuracy: 1.0000 - val_loss: 0.4650
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.3875 - val_accuracy: 1.0000 - val_loss: 0.4597
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.3821 - val_accuracy: 1.0000 - val_loss: 0.4536
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.3762 - val_accuracy: 1.0000 - val_loss: 0.4474
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3707 - val_accuracy: 1.0000 - val_loss: 0.4422
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.3646 - val_accuracy: 1.0000 - val_loss: 0.4376
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.3596 - val_accuracy: 1.0000 - val_loss: 0.4319
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.3541 - val_accuracy: 1.0000 - val_loss: 0.4263
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3486 - val_accuracy: 1.0000 - val_loss: 0.4207
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.3429 - val_accuracy: 1.0000 - val_loss: 0.4143
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3379 - val_accuracy: 1.0000 - val_loss: 0.4096
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.3326 - val_accuracy: 1.0000 - val_loss: 0.4041
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.3274 - val_accuracy: 1.0000 - val_loss: 0.3989
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.3223 - val_accuracy: 1.0000 - val_loss: 0.3938
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.3166 - val_accuracy: 1.0000 - val_loss: 0.3872
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.3122 - val_accuracy: 1.0000 - val_loss: 0.3821
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.3072 - val_accuracy: 1.0000 - val_loss: 0.3773
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.3019 - val_accuracy: 1.0000 - val_loss: 0.3714
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2974 - val_accuracy: 1.0000 - val_loss: 0.3673
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2923 - val_accuracy: 1.0000 - val_loss: 0.3616
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2874 - val_accuracy: 1.0000 - val_loss: 0.3579
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2829 - val_accuracy: 1.0000 - val_loss: 0.3524
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2780 - val_accuracy: 1.0000 - val_loss: 0.3469
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2736 - val_accuracy: 1.0000 - val_loss: 0.3429
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2688 - val_accuracy: 1.0000 - val_loss: 0.3385
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2644 - val_accuracy: 1.0000 - val_loss: 0.3333
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2597 - val_accuracy: 1.0000 - val_loss: 0.3280
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2553 - val_accuracy: 1.0000 - val_loss: 0.3235
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2510 - val_accuracy: 1.0000 - val_loss: 0.3192
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2465 - val_accuracy: 1.0000 - val_loss: 0.3147
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2424 - val_accuracy: 1.0000 - val_loss: 0.3104
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2382 - val_accuracy: 1.0000 - val_loss: 0.3049
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.2340 - val_accuracy: 1.0000 - val_loss: 0.2999
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2301 - val_accuracy: 1.0000 - val_loss: 0.2957
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2257 - val_accuracy: 1.0000 - val_loss: 0.2909
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2219 - val_accuracy: 1.0000 - val_loss: 0.2868
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2180 - val_accuracy: 1.0000 - val_loss: 0.2828
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2140 - val_accuracy: 1.0000 - val_loss: 0.2788
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2102 - val_accuracy: 1.0000 - val_loss: 0.2746
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2063 - val_accuracy: 1.0000 - val_loss: 0.2699
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.2027 - val_accuracy: 1.0000 - val_loss: 0.2660
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1987 - val_accuracy: 1.0000 - val_loss: 0.2615
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1954 - val_accuracy: 1.0000 - val_loss: 0.2576
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1918 - val_accuracy: 1.0000 - val_loss: 0.2537
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1883 - val_accuracy: 1.0000 - val_loss: 0.2499
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1847 - val_accuracy: 1.0000 - val_loss: 0.2456
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1812 - val_accuracy: 1.0000 - val_loss: 0.2413
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1782 - val_accuracy: 1.0000 - val_loss: 0.2376
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1750 - val_accuracy: 1.0000 - val_loss: 0.2340
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.1718 - val_accuracy: 1.0000 - val_loss: 0.2304
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1686 - val_accuracy: 1.0000 - val_loss: 0.2269
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1655 - val_accuracy: 1.0000 - val_loss: 0.2233
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1625 - val_accuracy: 1.0000 - val_loss: 0.2199
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.1596 - val_accuracy: 1.0000 - val_loss: 0.2165
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1566 - val_accuracy: 1.0000 - val_loss: 0.2131
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.1538 - val_accuracy: 1.0000 - val_loss: 0.2098

In [ ]:
from tensorflow.keras import optimizers

In [ ]:
opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)